
services:
  # Customer Experience Assessment Service (with ChromaDB integration)
  customer-experience-api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LOG_LEVEL=INFO
    depends_on:
      - chromadb
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    restart: unless-stopped

  # ChromaDB (Standalone)
  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    volumes:
      - ./chroma:/data
    restart: unless-stopped

  # Data Pipeline (optional)
  data-pipeline:
    build:
      context: .
      dockerfile: docker/Dockerfile.pipeline
    environment:
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - DATA_PATH=/app/data/DisneylandReviews.csv
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    depends_on:
      - chromadb
    restart: "no"

  # Jupyter Notebook (development)
  jupyter:
    build:
      context: .
      dockerfile: docker/Dockerfile.notebook
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=${JUPYTER_TOKEN:-disney}
    volumes:
      - ./notebooks:/app/notebooks
      - ./data:/app/data
      - ./src:/app/src
    restart: unless-stopped

